### ISSUE TITLE
Pi-Python (Pi-Ruby SDK Adaption)

### ISSUE THREAD

**Issue by Hascyll** [pi-apps/pi-ruby#3]
During the tests for the adaption of the Pi-Ruby SDK in Python the Server responses with:
```
<Response [400]>
{'error': 'too_many_cancelled_payments', 'error_message': 'Your app has too many cancelled payments.'}
```
Please increase the number of possible cancelled payments for the time of testing the new SDK (e.g. 7 days)

**Comment by aurelienshz** [comment]
This should have been increased enough to allow plenty of testing on the testnet. Feel free to reopen the issue if you're blocked again by the rate-limiting!
