### ISSUE TITLE
Error when sending text Memo instead of identifier Memo

### ISSUE THREAD

**Issue by rockcesar** [pi-apps/pi-ruby#4]
Error when sending text Memo instead of identifier Memo.

The error is that I sent Memo in text instead of Identifier. I modified this code, here:
https://github.com/pi-apps/pi-ruby/blob/c439f3434c6621b9aad644538cb6860ec35cc733/lib/pi_network.rb#L164

I changed like this:
<code>
memo = Stellar::Memo.new(:memo_text, transaction_data[:memo])
</code>

And I had this error, trying to complete:
<code>
{'error': 'verification_failed', 'verification_error': 'tx_memo_payment_identifier_mismatch'}
</code>

Then the transaction was verified by blockchain automatically, and when try to complete the pending payment, says this:
<code>
{'error': 'verification_failed', 'verification_error': 'payment_already_linked_with_a_tx'}
</code>

I can't complete. This is identifier of payment: 'jGCjzZqgg78B6Pf1wzYHFSBTqNIv'

And if I try to cancel it says:
<code>
{'error': 'payment_tx_present', 'error_message': 'You cannot cancel this payment, because an associated blockchain transaction has been recorded.'}
</code>

The payment has already a TXID:
```
1dc247528d680728aa2912e1a94c89b7b8f82d1a1495a003ace920186b720b77
```

This is my incomplete payments:

<code>
{'incomplete_server_payments': [{'identifier': 'jGCjzZqgg78B6Pf1wzYHFSBTqNIv', 'user_uid': '38633a57-2388-49e0-a000-e325ef03c451', 'amount': 1.0, 'memo': 'From app to user test', 'metadata': {'test': 'your metadata'}, 'from_address': 'GDV24GWXUSDUYU4N5W4YIEKJ7BW5DORBH7TVP46AERG4TV677USYBP3E', 'to_address': 'GAORGY7GWJYSARCO7KZH3QRX2FQKD25KQSTQJPKWE7WZTEBBHTSUDAA5', 'direction': 'app_to_user', 'status': {'developer_approved': True, 'transaction_verified': False, 'developer_completed': False, 'cancelled': False, 'user_cancelled': False}, 'transaction': {'txid': '1dc247528d680728aa2912e1a94c89b7b8f82d1a1495a003ace920186b720b77', 'verified': False, '_link': 'https://api.testnet.minepi.com/transactions/1dc247528d680728aa2912e1a94c89b7b8f82d1a1495a003ace920186b720b77%27%7D, 'created_at': '2023-01-22T16:32:06.468Z', 'network': 'Pi Testnet'}]}
</code>

**Comment by rockcesar** [comment]
Some pioneers and me, are doing a Python version of the this A2U ruby payment. That's why I'm testing:

https://github.com/pi-apps/LatinChain/blob/main/Pi_A2U_payment/pi_network.py

**Comment by aurelienshz** [comment]
Hi, this issue should have been fixed. The API now allows cancelling payments when the transaction which was submitted could not be correctly verified. This is indeed not something that should be automated in your code, and cancelling payments should not be taken lightly. But if and when, for some reason, an invalid transaction was submitted and can't be verified, you may cancel the payment to unblock your app.

**Comment by rockcesar** [comment]
Ok, thank you. That's great!.
